### ISSUE TITLE
FakeSuccessContinuationWrapper的调度问题

### ISSUE THREAD

**Issue by xiaocydx** [ParadiseHell/one#2]
#1 throwableResolver.resolve()看起来只是构建异常结果，在构建FakeSuccessContinuationWrapper时，传入拦截后的Continuation，解决resumeWith()的调度问题或许会更好。

```
import kotlin.coroutines.intrinsics.intercepted

FakeSuccessContinuationWrapper(
    (args.last() as Continuation<Any>).intercepted(),
    resolver as ThrowableResolver<Any>
 )
```

**Comment by ParadiseHell** [comment]
> #1 throwableResolver.resolve()看起来只是构建异常结果，在构建FakeSuccessContinuationWrapper时，传入拦截后的Continuation，解决resumeWith()的调度问题或许会更好。
> 
> ```
> import kotlin.coroutines.intrinsics.intercepted
> 
> FakeSuccessContinuationWrapper(
>     (args.last() as Continuation<Any>).intercepted(),
>     resolver as ThrowableResolver<Any>
>  )
> ```

谢谢，我改一下，我对协程的了解还不是很深入，今天学习到了，谢谢～～

**Comment by ParadiseHell** [comment]
@xiaocydx 我尝试了好半天都没办法调用 intercepted API, 我看 kotlin 的 github repo 确实有想过的 API, 但是我在 ide 里就是无法调用，最后在一个 `CoroutinesIntrinsicsH.kotlin_metadata` 里找到，但是就是无法调用，很奇怪，如果你有方式，还麻烦解答一下，谢谢。

不过之前的版本确实是有调度的问题，已经在 `FakeSuccessContinuationWrapper ` 里面通过 `runBloking(context)` 方式解决了。

**Comment by xiaocydx** [comment]
是没有导包吗，ide对这类API没有提示
```
import kotlin.coroutines.intrinsics.intercepted
```

**Comment by ParadiseHell** [comment]
import 不到，你可以？

**Comment by xiaocydx** [comment]
我可以导入，拉过项目，做了修改跑过。

**Comment by xiaocydx** [comment]
![20220306221003](https://user-images.githubusercontent.com/43429149/156926867-f4afe45d-2b09-431b-aa35-601fc330661d.png)

**Comment by ParadiseHell** [comment]
好的，我回家再看一下，很奇怪，我昨天试了半天都 import 不到。

**Comment by ParadiseHell** [comment]
@xiaocydx 我这边我的 ide 没办法提示我 intercepted 方法，但是强制输入就 OK 了，多谢多谢。
